{% set version = "2.0" %}

package:
  name: cmocean
  version: {{ version }}

source:
  url: https://github.com/matplotlib/cmocean/archive/{{ version }}.tar.gz
  sha256: bab61cbcd6a17d55f3351e210299ed7ad2117b47952d22fdddfbdd055c2ca75d

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - matplotlib

test:
  imports:
    - cmocean
  requires:
    - pytest

about:
  home: https://github.com/matplotlib/cmocean
  license: MIT
  license_file: LICENSE.txt
  summary: 'Colormaps for Oceanography'

extra:
  recipe-maintainers:
    - kthyng
    - ocefpaf
