{% set version = "1.0" %}

package:
    name: cmocean
    version: {{ version }}

source:
    fn: cmocean-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/c/cmocean/cmocean-{{ version }}.tar.gz
    sha256: 4ef81a2b2041628afad983ec67de5d4fd043670a90e416f4cfbffe23c3c9beec

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - matplotlib

test:
    imports:
        - cmocean
    requires:
        - pytest

about:
    home: https://github.com/matplotlib/cmocean
    license: MIT
    summary: 'Colormaps for Oceanography'

extra:
    recipe-maintainers:
        - ocefpaf
