travis:
  secure:
    BINSTAR_TOKEN: dIBVUNgJoA/oQXidflxu0mF+FD/lXzx9V8Tl/J+tl0sK0Gp4dkz3xwLLUrErF9GkKaY9mJikEM1ZYOGvYg39LjX4XrFnoxABUSesxDKenDeiDriQ0ygEt7ORnhCkuDD9HjHzkv/+Jcl+oz49ksmcjpODvuzpYbfR40u8zZIaJgUBe2rPJegeM1PddOILFRhoNw//A9JM/6GnVjQWWDDmRKJLBp0Txv84fEjQzpjeD4KkVV9eqvsQV1fryuWZSmSVoIZsHz5/ZAnDBS68o7E2erahcVekF3LQT3xCmVV329BUCch+ZyNBSdI6hvXhUGxWmi0ywUf8igygwd0GqywNqU6N0Vt1aaaJK4N6uPw7sX1EgPYkYwQzcPduEvqcCxzq9iqpZqIGg6shR10Wqa9K/fzqrptkoDmALPkTuz2P5VM56GisAD1BrkLM31C+NmyfeAUjYxWoJGeCPaYi+46dShABHMfJjFlZJlXn26d1VFQQvEDs0LC7Oi5Vgrcoo+vmGIrgG/fbNcGmPxWAgyeAXPf4nKvW5feiXcdHL3UEhLMee8/LkFKgXGjHoj13CPZ2mgeXfyaT/hn6KHcA4cnWaJQWqtBV7r1IPaThoCVss20f5H9vlkxEbfvRiCco+ETyrPl3tnp4aiL0nPVvnQPf8HWrF0KeMs/+9Q2h3SNGnT4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
