travis:
  secure:
    BINSTAR_TOKEN: GBUCSf4K/508oXiwHO/Fc5jz6ZDo1+XCUThHaDZ3XJAeKNl9ML3TuPlsd1vL4q2fYJjtV7aXlR1+pAr3suO+5vL7BWccnMh2tQjlSVpMtySYBRf6wBmKun4IdCaiR6VSH4QdV0cNgHST+mjRfFDJtblKw5vCnvXNv1zSOr2fsE4R2qGK3eIzcKpytt74Jrz1SnPb0le/a1ZQox6Ei6OPMI/yzKZfQxoA/B5RWtqJkPNtOZuFPl89V5Y6TCE65xWhXeocKKK+pSP5dgsQuc9pSenkskN39UrqVBz99x0FB9050Q/goRSUyIL+ahyasmf0dlWYQ9wk3XZbIsQXPCzPlv/MmITIYI1GO6ATnJqooya0CBWbo8JsTujiSr43BzqS9adnrYp0ZPtDPz+rt0LUBjkuHsGvvy/uIZDkB8JsdycMhkwOUfgNtGJtEQNUdIaZHEGGe/zRqcoAqAlvO/ByT1/9yGpKinhIjUTitWj6U/1oukIEhngoEuPRxAYwcD1Bi84JBQH2xGlSmcC+bTlIIPVmVl8Az1iu3qbVyg0SDIP0O9RCD4fJcEzseW87sju7eNEm6fZIHnbhChWAt4DmOm5rvSRi+2XZTu5tM4NX8tGyX19MteUbZ341i/LazW6DUXLlTwN2AeyYsxS6NDWTnAmvuP9dHOKsb8Jd/CKYijk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
