travis:
  secure:
    BINSTAR_TOKEN: NO0/4R7HnvtvC/GRK5Qgj8AXAwgo95yr9sIE9+2DTSFpnbc2QtOT3EuGvez5CV4bnt96YgAc3N5j8dqTFsuguWuUFB8NTZH9PcbacvdNR4UR4HOn1TAzjhCUBI1iZXDD/T6yEMI82Ytjr5RTgRRTiS3f3bLuPxh1aYrdb2ih8FKRDrw8h/gebmG4fo6P8YKMTu+hqgaY1LGyEofl93Q1tSNe0kSRCxcsz/tWXBDG1WDd2dmfLiAyHmyUM43zinfyblDVR03VcCiYC2qOQr2Dzb08UjBmeUxWoTFt99hCyYScPDP/cEyYDxdyZpf/fWcWrzdKZz0BUn+49qqKelmboIt4MVaKrajy9ASGR/gWoAmw9a2f2DNEb8PVX+GA/ramXLmYKGApKVSCmTLgQ2ZOR9D445CS+JvLL1OVpWXDFxk9Ti6pepcudU245BeoYmqjsHeFjLaOet36GVRvz8Yvl6xHh7AIqAtQrtfhiYjMZdKdM9VC+uufGh8YcVemIf0KIJFqHBx18nrlKUaMcwggByomFcgAKXTY3kPrfufHVS1UtTnn26GCkQoQbaRi+oK+7hr7lTnZy1ZcLPF0zaaf4Y9O4EstjU82a4AoS/RLzeI83WnkLFuL4UKZ6V2aUYwV7SNGhw8JzYa6tgawtA/UkngULtanWoc2VvA4gePB9Cs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
